name: Veracode Static Pipeline Scanner

on:
  workflow_call:
    inputs:
      policy_name:
        required: true
        type: string
      profile_name:
        required: true
        type: string  
      action:
        required: true
        type: string    

  
jobs:
  pipeline_scan:
    runs-on: ubuntu-latest
    name: pipeline scan

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      # get the compiled binary from a previous job
      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: veracode-artifact
          path: ./veracode_artifact_directory
      
      - name: Get the name of the downloaded files
        run: |
          artifact_file=$(ls -1 ./veracode_artifact_directory | head -n 1)
          echo "veracode_artifact=$artifact_file" >> $GITHUB_ENV

      # run the pipeline scan action
      - name: Veracode Pipeline-Scan
        id: pipeline-scan
        uses: testallrepos/Veracode-pipeline-scan-action@main
        with:
          appname: ${{ inputs.profile_name }}
          createprofile: true
          policy: ${{ inputs.policy_name }}
          version: '${{ github.run_id }}'
          filepath: ./veracode_artifact_directory/${{ env.veracode_artifact }}
          veracode_policy_name: ${{ inputs.policy_name }}
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          action:  ${{ inputs.action }}
          #scanpollinginterval: 30
          scantimeout: 15
          include: ${{ inputs.modules_to_scan }}
          failbuild: true
